### ISSUE TITLE
Using Cached Results if Update Fails

### ISSUE THREAD

**Issue by kerns** [leowebguy/craft-currency-converter#1]
I'd been looking for exactly this plugin and even asked out loud about it on our Discord when a day or two later you published this. It's really appreciated.

One question I have is with regard to reliability of the API when using the free tier. If the conversion attempt fails or the request is not fulfilled do due to too many requests, do we fallback to a cached version?

**Comment by leowebguy** [comment]
correct! the cache prevents the over usage of the api.

thanks for the appreciation.

leo

**Comment by kerns** [comment]
Perfect. Really cool. And is the request made once (according to preferences set with the plugin) per site ...not per user? So keeping within the limits even for medium sized site should be fine if you set it to update every day? But again, if the API is blocked or discontinued it won't make an ass of itself...which is great :-)

The only other event then that could spell disaster would be if the API was changed or messed with in some way that returned a bad result. So maybe you could consider implementing some threshold for this...say, to pass on updating the cached version if the difference of the new value from the previous value exceeds 50%. Or maybe blocking any value returned if it is = to zero. Just some additional safeguards could be great.

Thanks again.
