### ISSUE TITLE
Dependency Conflict

### ISSUE THREAD

**Issue by kerns** [leowebguy/craft-currency-converter#1]
<img width="749" alt="Screen Shot 2021-02-02 at 13 52 16" src="https://user-images.githubusercontent.com/20254/106602906-ea2b4400-655d-11eb-8689-412a9669461e.png">

Any idea how to resolve this issue in upgrading to 3.6?

> Problem 1
> - Installation request for craftcms/cms 3.6.2 -> satisfiable by craftcms/cms[3.6.2].
> - Conclusion: remove leowebguy/craft-currency-converter 1.0.2
> - leowebguy/craft-currency-converter 1.0.2 requires guzzlehttp/guzzle 6.5.2 -> satisfiable by guzzlehttp/guzzle[6.5.2].
> - leowebguy/craft-currency-converter 1.0.2 requires guzzlehttp/guzzle 6.5.2 -> satisfiable by guzzlehttp/guzzle[6.5.2].
> - Can only install one of: guzzlehttp/guzzle[6.5.2, 6.5.5].
> - Can only install one of: guzzlehttp/guzzle[6.5.5, 6.5.2].
> - Can only install one of: guzzlehttp/guzzle[6.5.5, 6.5.2].
> - craftcms/cms 3.6.2 requires guzzlehttp/guzzle ^6.5.5|^7.2.0 -> satisfiable by guzzlehttp/guzzle[7.2.0, 6.5.5].
> - Conclusion: don't install guzzlehttp/guzzle 7.2.0
> - Installation request for leowebguy/craft-currency-converter 1.0.2 -> satisfiable by leowebguy/craft-currency-converter[1.0.2].

**Comment by kerns** [comment]
Maybe it would be fixed by updating `"guzzlehttp/guzzle": "6.5.2"` to `"guzzlehttp/guzzle": "6.5.5"` ...or even just         "guzzlehttp/guzzle": "^6.5.2"?

**Comment by leowebguy** [comment]
sorry kerns, for some reason I didn't get the notification. it's fixed now.
