### ISSUE TITLE
Last Craft Update Broke Currency Converter

### ISSUE THREAD

**Issue by kerns** [leowebguy/craft-currency-converter#2]
I have a toggle for using local rates in my UI. But using your plugin now throws a Server error: 

`GET https://free.currconv.com/api/v7/convert?q=DKK_EUR&compact=ultra&apiKey=e73476becdb9abexxxx resulted in a 503 Service Unavailable response:`

<img width="756" alt="Screen Shot 2020-03-30 at 11 57 29" src="https://user-images.githubusercontent.com/20254/77899976-a56bb800-727d-11ea-927d-36e3b84484d2.png">

Maybe the service is down?

---
Currency Converter | 1.0.1
-- | --
PHP version | 7.4.3
-- | --
Darwin 19.3.0
MySQL 5.6.47
GD 7.4.3
Craft Pro 3.4.11

**Comment by leowebguy** [comment]
probably. checking today.
thanks!

**Comment by kerns** [comment]
Can we covert to this service? Looks so much more reliable. And free up to 1000 requests a month. Set the caching rate to min 1 hour and it is still within their limit.

https://rapidapi.com/fixer/api/fixer-currency

<img width="1030" alt="Screen Shot 2020-04-01 at 22 57 42" src="https://user-images.githubusercontent.com/20254/78185974-3a340880-746c-11ea-94e3-131a3753fbba.png">

**Comment by leowebguy** [comment]
sure!

let me do that.

**Comment by kerns** [comment]
WAIT. This one seems completely free. Let's definitely find a stable free and open one. :-)

https://rapidapi.com/natkapral/api/currency-converter5

**Comment by kerns** [comment]
This deserves a littler research! :-)

https://rapidapi.com/search/currency%20converter

**Comment by leowebguy** [comment]
got it.

let me try this.

**Comment by leowebguy** [comment]
all set.

**Comment by kerns** [comment]
Incredible. Let me know if you want me to test or when it goes live.

**Comment by leowebguy** [comment]
update should be available

https://github.com/leowebguy/craft-currency-converter <https://github.com/leowebguy/craft-currency-converter>

**Comment by kerns** [comment]
Fantastic. Look forward to try!

**Comment by kerns** [comment]
It still looks (on the user-facing side) like you're using the previous service – but if I understand you then you are accepting a rapidapi key in this field? :-)

<img width="913" alt="Screen Shot 2020-04-02 at 14 23 45" src="https://user-images.githubusercontent.com/20254/78249164-2e892600-74ee-11ea-85bb-044d6d54bc09.png">

**Comment by kerns** [comment]
I can't find any evidence of the update? Maybe Craft reviews updates before they come into the store?

**Comment by leowebguy** [comment]
should be all set.

I have it updated in packagist > https://packagist.org/packages/leowebguy/craft-currency-converter <https://packagist.org/packages/leowebguy/craft-currency-converter>

release tag is in place > https://github.com/leowebguy/craft-currency-converter/releases/tag/v1.0.2 <https://github.com/leowebguy/craft-currency-converter/releases/tag/v1.0.2>

**Comment by leowebguy** [comment]
closing.

**Comment by kerns** [comment]
Still only seeing 1.0.1 in the official store. I continue to clear my cache and reload. :-)

**Comment by kerns** [comment]
Still only seeing 1.0.1. Are you sure you pushed this? 🤔
