### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by eyekiller-hub** [leowebguy/craft-currency-converter#3]
Hi 

Will there be a Craft 4 version soon?

Regards
Jamie

**Comment by leowebguy** [comment]
Latest version already is.

**Comment by mark-adigital** [comment]
Hi @leowebguy  - thanks for the plugin. The code updates to make it Craft 4 compatible may have been done, but I'm not sure these have been picked up correctly as I still see the plugin as 'Not ready' when looking at the Craft 4 upgrade section of utilities:

<img width="1858" alt="Screenshot 2022-08-24 at 11 24 47" src="https://user-images.githubusercontent.com/30312669/186396040-f16e1376-47e6-4355-a62f-c1585d0b28d9.png">

**Comment by leowebguy** [comment]
Hey @mark-adigital version 1.0.4 is already C4 ~ just tag that in your composer.json

**Comment by mark-adigital** [comment]
Thanks, I'm sure the plugin is now compatible - I was just flagging that the Craft 4 Upgrade tab in utilities doesn't seem to know you've done that, not sure if that points to some kind of declaration issue or something.
